### ISSUE TITLE
Correção do Readme

### ISSUE THREAD

**Issue by jdmanzur** [GuiMilani/covid-sorocaba#3]
oi gente, estou corrigindo o projeto de vocês para ser colocado na revista do Hackerspace. O repositório e o readme estão bem completos, mas há frases que estão em primeira pessoa. Será que vocês poderiam corrigir esses pedaços para que o repositório seja colocado na revista?
Obrigada :D

**Comment by GuiMilani** [comment]
Olá Jade, corrigido. Caso sejam necessárias outras mudanças me notifique, por favor.
Obs: O site está com bugs e eu não pude resolve-los nesse último semestre, mas pretendo corrigir na próxima semana.
